# Generated by Django 5.1.6 on 2026-03-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, choices=[('qarshi_1_mitti', 'Qarshi 1-mitti tuman'), ('qarshi_2_mitti', 'Qarshi 2-mitti tuman'), ('qarshi_3_mitti', 'Qarshi 3-mitti tuman'), ('qarshi_4_mitti', 'Qarshi 4-mitti tuman'), ('qarshi_5_mitti', 'Qarshi 5-mitti tuman'), ('qarshi_6_mitti', 'Qarshi 6-mitti tuman'), ('qarshi_7_mitti', 'Qarshi 7-mitti tuman')], db_index=True, max_length=32),
        ),
    ]
